name: Build, Test and Dry Run Publish

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Dry run publish to JSR
      run: npx jsr publish --dry-run

    - name: Dry run publish to NPM
      run: npm publish --dry-run
